### ISSUE TITLE
VPCOptions in ElasticSearch Domain

### ISSUE THREAD

**Issue by smrutimandal** [flomotlik/formica#111]
I am trying to create an Elastic Search Domain and the VPCOptions property is being marked invalid. Below is the config I am trying to apply. 

 ```
 TestElasticsearchDomain:
    Properties:
      ElasticsearchVersion: !Ref ElasticsearchVersion
      ElasticsearchClusterConfig:
        InstanceCount: !Ref ElasticsearchInstanceCount
        InstanceType: !Ref ElasticsearchInstanceSize
      EBSOptions:
        EBSEnabled: true
        VolumeSize: 35
        VolumeType: "gp2"
    Type: AWS::Elasticsearch::Domain
    VPCOptions:
      SubnetIds: 
        - !Split [',', {'Fn::ImportValue': !Sub '${ParentVPCStack}-SubnetsPrivate'}]
      SecurityGroupIds:
        - !GetAtt PeerDatabaseConnectionGroup.GroupId
```
I am getting the following error.
`Invalid template resource property 'VPCOptions'`

I am using formica 0.9.3.

Is VPCOptions a supported property?
