### ISSUE TITLE
New Module Syntax

### ISSUE THREAD

**Issue by flomotlik** [flomotlik/formica#74]
[The Module Syntax](https://theserverlessway.com/tools/formica/modules/) is very cumbersome at the moment and breaks away from the CloudFormation syntax, making it a bit of a weird addition to Formica. To solve that I've been thinking about a New Module Syntax that should be a lot closer to standard CloudFormation.

## Basic Syntax

Old Syntax:
```
Modules:
  - path: modules/dns
    template: cname
    vars:
      source: flomotlik.me
      target: somewhere.else.me
      hostedZone: FormicaHostedZone
```

The Problem with this old syntax is that it introduces a new module syntax that is just weird and doesn't look like any other resource.

Instead we're introducing a new resource property `From`:

```
Resources:
  WebsiteHosting:
    From: DNS::Cname
    Properties:
      Source: flomotlik.me
      Target: somewhere.else.me
      HostedZone: FormicaHostedZone
```

`From` loads templates from the filesystem (and potentially built-in modules or something else in the future). Only directories that you're adding through the `--modules` argument are searched so you can drop the path part of the module section in the old example. We'll automatically turn the `FROM` to lower case and compare to file system on lower case and select matching paths to make it easier so you don't have to use CamelCase on the file system.

In the above case the file would be stored in `modules/dns/cname.template.yaml`. We're setting the `modules` folder as a cli argument and then match the `FROM` arguments.

## Multiple Uses of a Module

This works perfectly fine for Modules that should only be used once in a template, but the problem some modules have to be used multiple times in a template (e.g. CNAMEs), so we need a way to parameterise them. In the old implementation we didn't have a custom name given to an instance of a module, so we needed to use some Variable, e.g. the source in a cname. Because we're now using `LogicalNames` in the same way we're using them for our other CloudFormation resources and those have to be unique we can use them and expose them as a variable.

In a module file we expose the name in a `module_name` that you can then use to make your modules easily reusable and make Ref and other module internal relations work.

```
Resources:
  {{ module_name  }}CNameRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId:
        Ref: {{ module_name  }}HostedZone
      Name: {{ source }}
      Type: CNAME
      TTL: '43200'
      ResourceRecords:
        {% for target in targets | mandatory %}
          - {{ target }}
        {% endfor %}
```

In the future we could implement some automated mechanism for that, e.g. read all `LogicalNames` for a module and replace any Refs or GetAtts, but this will have to be discussed separately.

## Built-In Modules

In the future this would allow to add Formica built-in modules library, like for DNS or other common use cases, e.g. with a prefix like `Formica`.

```
Resources:
  WebsiteHosting:
    From: Formica::DNS::Cname
    Properties:
      Source: flomotlik.me
      Target: somewhere.else.me
      HostedZone: FormicaHostedZone
```
